[tools]
# Security & Policy Validation
trivy = "0.71.0"
conftest = "0.68.2"
cosign = "3.1.1"
trufflehog = "3.95.6"
"pipx:checkov" = "3.3.1"
"pipx:pre-commit" = "4.6.0"
"pipx:yamllint" = "1.38.0"
"pipx:cfn-lint" = "1.51.5"


# IaC & Configuration Management
terraform = "1.5.7"
ansible = "9.5.1"
"pipx:ansible-lint" = "26.4.0"
terragrunt = "1.0.8"
tflint = "0.63.1"
infracost = "0.10.44"
terraform-docs = "0.24.0"

# Cloud Services
awscli = "2.15.30"
azure-cli = "2.87.0"
"pipx:aws-sam-cli" = "1.162.1"

# Kubernetes & Containers
kubectl = "1.30.1"
kubectx = "0.9.5"
k9s = "0.32.4"
helm = "4.2.1"
kustomize = "5.8.1"
kube-linter = "0.8.3"
helm-docs = "1.14.2"

# Local Testing & Mocking
k3d = "5.6.3"
act = "0.2.62"

# Runtimes / Programming Languages
node = "20.12.2"
python = "3.14.6"
go = "1.26.4"

# CLI Utilities
fzf = "0.73.1"
jq = "1.8.1"
bat = "0.26.1"