---
- name: Tflint 실행 가능 여부 확인
  ansible.builtin.command: which tflint
  register: tflint_check
  failed_when: false
  changed_when: false

- name: Tflint 플러그인 설정 및 다운로드 갱신
  when: tflint_check.rc == 0
  block:
    - name: Tflint 저장소 디렉토리 생성
      ansible.builtin.file:
        path: "{{ role_path }}/../../../stow/tflint"
        state: directory
        mode: '0755'

    - name: Tflint 플러그인 초기화 및 다운로드 (--init)
      ansible.builtin.command: tflint --init --config "{{ role_path }}/../../../stow/tflint/.tflint.hcl"
      register: tflint_init_result
      changed_when: "'Installing' in tflint_init_result.stdout"
